common: &common
  host: <%= ENV['DB_HOST'] || '127.0.0.1' %>
  template: template1
  adapter:  postgresql
  encoding: unicode
  pool:     <%= ENV['DB_CONCURRENCY'] || 10 %>
  <% if ENV['DB_PORT'].present? %>
  port:     <%= ENV['DB_PORT'] %>
  <% end %>
  timeout: 5000
  username: <%= ENV['DB_USER_NAME'] %>
  password: <%= ENV['DB_PWD'] || '' %>
  schema_search_path: "public,shared_extensions"

development:
  <<: *common
  database: boilerplate_development

test:
  <<: *common
  database: boilerplate_test

production:
  <<: *common
  database: boilerplate_production
